ktor {
    application {
        modules = [ org.rainbowhunter.adminpanel.core.ApplicationKt.module ]
    }
    deployment {
        port = 8080
        port = ${?PORT}
    }
}

adminpanel {
    db {
        path = "data/admin-panel.db"
        path = ${?ADMINPANEL_DB_PATH}
    }
    agents {
        registrationToken = "change-me-in-production"
        registrationToken = ${?ADMINPANEL_AGENT_REGISTRATION_TOKEN}
        heartbeatTimeoutSeconds = 30
        heartbeatTimeoutSeconds = ${?ADMINPANEL_AGENT_HEARTBEAT_SECONDS}
    }
}
